name: Build & deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies 🔧
        run: npm ci

      - name: Build 🏭
        run: |
          npm run build
          mkdir build

          sed -e "s~<head>~<head><base href=\"/tws24-fullstack-rust-slides/\" />~g" index.html > build/index.html
          mv {slides.md,css,dist,pitc-revealjs-theme,plugin} build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
